ERROR 29 [2018-08-22 00:15:22,697] control.Store - [1534868122697]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:25)
	at control.Store.doStore(Store.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:97)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 72 [2018-08-22 00:39:07,619] util.JdbcMethod.StoreJdbc - This is error:
java.sql.SQLException: No value specified for parameter 9
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:910)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:1737)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1575)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1519)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1504)
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:59)
	at control.Store.doStore(Store.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:97)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 29 [2018-08-22 13:41:13,842] control.Store - [1534916473842]Store doStore error
redis.clients.jedis.exceptions.JedisDataException: value sent to redis cannot be null
	at redis.clients.util.SafeEncoder.encode(SafeEncoder.java:28)
	at redis.clients.jedis.Client.exists(Client.java:61)
	at redis.clients.jedis.Jedis.exists(Jedis.java:178)
	at util.redisutil.RedisOperating.exists(RedisOperating.java:116)
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:41)
	at control.Store.doStore(Store.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:96)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 72 [2018-08-22 13:53:55,168] util.JdbcMethod.StoreJdbc - This is error:
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry '18222293350__1' for key 'PRIMARY'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3283)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1332)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1604)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1519)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1504)
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:59)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 15:36:32,446] control.Store - [1534923392446]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 16:01:59,578] control.Store - [1534924919578]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 16:19:29,111] control.Store - [1534925969111]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 16:38:29,827] control.Store - [1534927109827]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 73 [2018-08-22 16:49:28,130] util.JdbcMethod.StoreJdbc - This is error:
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry '18222293350__1' for key 'PRIMARY'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3283)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1332)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1604)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1519)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1504)
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:60)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 73 [2018-08-22 16:49:31,850] util.JdbcMethod.StoreJdbc - This is error:
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry '18222293350__1' for key 'PRIMARY'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3283)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1332)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1604)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1519)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1504)
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:60)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 73 [2018-08-22 16:49:34,608] util.JdbcMethod.StoreJdbc - This is error:
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry '18222293350__1' for key 'PRIMARY'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3283)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1332)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1604)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1519)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1504)
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:60)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 16:55:36,085] control.Store - [1534928136085]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 17:01:45,439] control.Store - [1534928505439]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 17:02:31,637] control.Store - [1534928551637]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 17:15:48,344] control.Store - [1534929348344]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 22:18:44,006] control.Store - [1534947524006]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 22:20:36,137] control.Store - [1534947636137]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 22:22:56,907] control.Store - [1534947776907]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 22:23:28,683] control.Store - [1534947808683]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 22:38:28,679] control.Store - [1534948708679]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 22:54:04,415] control.Store - [1534949644415]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 22:54:07,512] control.Store - [1534949647512]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 23:18:04,039] control.Store - [1534951084039]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 23:49:46,492] control.Store - [1534952986492]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 23:49:50,607] control.Store - [1534952990607]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 23:50:18,498] control.Store - [1534953018498]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR 32 [2018-08-22 23:50:34,434] control.Store - [1534953034434]Store doStore error
java.lang.NullPointerException
	at util.JdbcMethod.StoreJdbc.insertGoods(StoreJdbc.java:26)
	at control.Store.doStore(Store.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mysevlete.ServletTest.doServlet(ServletTest.java:94)
	at mainServer.WorkRunable.run(WorkRunable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
